module.exports = {
    docs: [
        {
            type: 'autogenerated',
            dirName: 'home'
        },
        'glossary',
        {
            type: 'category',
            label: 'API',
            items: [{ type: 'autogenerated', dirName: 'api' }]
        },
        {
            type: 'category',
            label: 'Customization',
            items: [{ type: 'autogenerated', dirName: 'customization' }]
        },
        {
            type: 'category',
            label: 'Integrations',
            link: { type: 'doc', id: 'integrations/index' },
            items: [
                {
                    type: 'category',
                    label: 'ERP, Finance & Master Data',
                    items: [
                        'integrations/adnet',
                        'integrations/adsolutions',
                        'integrations/granatum',
                        'integrations/jasmin',
                        'integrations/kamul',
                        'integrations/media360',
                        'integrations/mms',
                        'integrations/omie',
                        { type: 'category', label: 'Primavera', link: { type: 'doc', id: 'integrations/primavera/index' }, items: ['integrations/primavera/reference'] },
                        'integrations/publi',
                        { type: 'category', label: 'Sage', link: { type: 'doc', id: 'integrations/sage/index' }, items: ['integrations/sage/reference'] },
                        'integrations/toconline',
                        'integrations/vbd',
                        'integrations/vbs',
                        'integrations/wk-radar',
                        { type: 'category', label: 'iSAP', link: { type: 'doc', id: 'integrations/isap/index' }, items: ['integrations/isap/job-maintenance'] }
                    ]
                },
                {
                    type: 'category',
                    label: 'Job & Production Management',
                    items: [
                        'integrations/7log',
                        'integrations/active-collab',
                        'integrations/automations',
                        'integrations/azure-devops',
                        { type: 'category', label: 'CETA', link: { type: 'doc', id: 'integrations/ceta/index' }, items: ['integrations/ceta/reference'] },
                        'integrations/client-and-agencies',
                        'integrations/hubspot',
                        { type: 'category', label: 'JAM', link: { type: 'doc', id: 'integrations/jam/index' }, items: ['integrations/jam/reference'] },
                        'integrations/visto',
                        'integrations/wms',
                        'integrations/zappier'
                    ]
                },
                {
                    type: 'category',
                    label: 'HR & People',
                    items: [
                        'integrations/adp',
                        'integrations/bamboo',
                        'integrations/cs',
                        { type: 'category', label: 'EAS', link: { type: 'doc', id: 'integrations/eas/index' }, items: ['integrations/eas/reference'] },
                        'integrations/hr-link',
                        { type: 'category', label: 'Reach', link: { type: 'doc', id: 'integrations/reach/index' }, items: ['integrations/reach/reference'] },
                        { type: 'category', label: 'UtilPro', link: { type: 'doc', id: 'integrations/utilpro/index' }, items: ['integrations/utilpro/reference'] },
                        'integrations/workday-informatica'
                    ]
                },
                {
                    type: 'category',
                    label: 'Time & Timesheets',
                    items: ['integrations/vbs-timesheet', 'integrations/gsp-dynamic-timesheet-importer', 'integrations/timely']
                },
                {
                    type: 'category',
                    label: 'Creative & Collaboration',
                    items: [
                        'integrations/ziflow',
                        'integrations/zonza',
                        'integrations/microsoft-teams',
                        'integrations/siphon',
                        'integrations/sitecore',
                        'integrations/swivle',
                        {
                            type: 'category',
                            label: 'Cloud Storage',
                            link: { type: 'doc', id: 'integrations/cloud-storage/cloud-storage' },
                            items: ['integrations/cloud-storage/box', 'integrations/cloud-storage/box_old', 'integrations/cloud-storage/google-drive', 'integrations/cloud-storage/microsoft-sharepoint']
                        }
                    ]
                },
                {
                    type: 'category',
                    label: 'Identity & Access',
                    items: [
                        {
                            type: 'category',
                            label: 'Single Sign-On',
                            link: { type: 'doc', id: 'integrations/single-sign-on-sso/sso-configuration' },
                            items: ['integrations/single-sign-on-sso/google-suite', 'integrations/single-sign-on-sso/microsoft-entra', 'integrations/single-sign-on-sso/okta']
                        },
                        'integrations/azure-ad-blocker'
                    ]
                },
                {
                    type: 'category',
                    label: 'Reporting & Data',
                    items: ['integrations/powerbi', 'integrations/custom-table-importer', 'integrations/api']
                }
            ]
        },
        {
            type: 'category',
            label: 'AI',
            items: [{ type: 'autogenerated', dirName: 'ai' }]
        },
        {
            type: 'category',
            label: 'SDK',
            link: { type: 'doc', id: 'sdk' },
            items: [{ type: 'autogenerated', dirName: 'sdk' }]
        },
        {
            type: 'category',
            label: 'To Review',
            className: 'hidden',
            link: {
                type: 'generated-index',
                title: 'To Review Files',
                description: 'Below you can find a list of documents that were migrated from previous Help Center or Knowledge Base, and that require being reviewed, before pushing it into a category, and available for users.',
                slug: '/to-review',
                keywords: ['guides']
            },
            items: [{ type: 'autogenerated', dirName: 'to-review' }]
        }
    ],
    university: [{ type: 'autogenerated', dirName: 'university' }],
    trust: [{ type: 'autogenerated', dirName: 'trust' }]
};
