module.exports = {
    docs: [
        {
            type: 'category',
            label: 'Craft',
            items: [
                {
                    Panels: [
                        {
                            Grid: [
                                'craft/panels/grid/set-columns'
                            ]
                        },
                        {
                            Form: [
                                'craft/panels/form/set-items'
                            ]
                        }
                    ],
                },
                {
                    Workspaces: [
                        {
                            type: 'autogenerated',
                            dirName: 'craft/workspaces'
                        }
                    ]
                },
                {
                    Automations: [
                        {
                            type: 'autogenerated',
                            dirName: 'automations'
                        }
                    ]
                }
            ]
        },
        {
            type: 'category',
            label: 'Advanced',
            items: [

                {
                    SDK: [
                        {
                            Document: [
                                {
                                    type: 'autogenerated',
                                    dirName: 'sdk/document'
                                }
                            ]
                        },
                        'sdk/execute-api',
                        {
                            Shell: [
                                {
                                    type: 'autogenerated',
                                    dirName: 'sdk/shell'
                                }
                            ]
                        },
                        'sdk/store',
                        {
                            UI: [
                                {
                                    type: 'autogenerated',
                                    dirName: 'sdk/ui'
                                }
                            ]
                        },
                        {
                            Utils: [
                                {
                                    type: 'autogenerated',
                                    dirName: 'sdk/utils'
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            type: 'category',
            label: 'Integrations',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'integrations'
                }
            ]
        }
    ],
    university: [
        {
            type: 'autogenerated',
            dirName: 'university'
        }

    ]
};
