module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Craft',
      items: [
        {
          Panels: [
            {
              Grid: [
                'craft/panels/grid/set-columns'
              ]
            },
            {
              Form: [
                'craft/panels/form/set-items'
              ]
            }
          ],
        },
        'craft/craft-workspaces'
      ]
    },
    {
      type: 'category',
      label: 'Advanced',
      items: [
        {
          SDK: [
            'sdk/introduction',
            {
              UI: [
                'sdk/ui',
                'sdk/ui-grid',
                'sdk/ui-selectBox',
                'sdk/ui-buttons',
                'sdk/ui-alert',
                'sdk/ui-tooltip',
                'sdk/ui-workspaces'
              ]
            },
            {
              Document: [
                'sdk/document',
                'sdk/assignments',
                'sdk/holidays',
                'sdk/customTables',
                'sdk/clients',
                'sdk/users',
                'sdk/estimates'
              ]
            }
          ]
        },
        'automations',
        'queries',
        'types'
      ]
    },
    {
      type: 'category',
      label: 'Integrations',
      items: [
        'integrations/hr-link'
      ]
    },
     {
          type: 'category',
          label: 'University',
          items: [
            {
              type: 'autogenerated',
              dirName: 'university'
            }
          ]
        }
  ],
  api: {}
};
