module.exports = {
    docs: [
        {
            type: 'autogenerated',
            dirName: 'home'
        },
        {
            type: 'category',
            label: 'API',
            items: [{ type: 'autogenerated', dirName: 'api' }]
        },
        {
            type: 'category',
            label: 'Customization',
            items: [{ type: 'autogenerated', dirName: 'customization' }]
        },
        {
            type: 'category',
            label: 'Integrations',
            items: [{ type: 'autogenerated', dirName: 'integrations' }]
        },
        {
            type: 'category',
            label: 'SDK',
            link: { type: 'doc', id: 'sdk' },
            items: [{ type: 'autogenerated', dirName: 'sdk' }]
        },
        {
            type: 'category',
            label: 'To Review',
            className: 'hidden',
            link: {
                type: 'generated-index',
                title: 'To Review Files',
                description: 'Below you can find a list of documents that were migrated from previous Help Center or Knowledge Base, and that require being reviewed, before pushing it into a category, and available for users.',
                slug: '/to-review',
                keywords: ['guides']
            },
            items: [{ type: 'autogenerated', dirName: 'to-review' }]
        }
    ],
    university: [{ type: 'autogenerated', dirName: 'university' }],
    trust: [{ type: 'autogenerated', dirName: 'trust' }]
};